spring.application.name=hmdback27
server.port=8099
spring.data.mongodb.uri=mongodb://localhost:27017/dbiqraa27
server.address=0.0.0.0
server.servlet.encoding.enabled=true
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true